services:
    web:
        container_name: apitest
        image: apitest
        environment:
          - TZ=Asia/Seoul
        restart: always
        ports:
          - "8000:8000"
        build: 
            context: ./dockerfiles
            dockerfile: Dockerfile
        volumes:
          - ./:/workspace
        working_dir: /workspace
        # network_mode: "host"\
        # entrypoint: /bin/sh
        tty: true
        stdin_open: true
        extra_hosts:
        - "host.docker.internal:host-gateway"
        # command: uvicorn main:app --reload --host=0.0.0.0 --port=10000 --workers=1
        # command: gunicorn main:app -w 4 -k uvicorn.workers.UvicornWorker -b 0.0.0.0:10000