services:
    web:
        container_name: apitest
        image: apitest
        environment:
          # TZ=Asia/Seoul
          DB_NAME: postgres
          DB_USER: postgres
          DB_PASSWORD: postgres
          DB_HOST: postgres
          
        restart: always
        ports:
          - "8000:8000"
        build: 
            context: ./dockerfiles
            dockerfile: Dockerfile
        volumes:
          - ./:/workspace
        working_dir: /workspace
        # network_mode: "host"\
        # entrypoint: /bin/sh
        tty: true
        stdin_open: true
        extra_hosts:
        - "host.docker.internal:host-gateway"
        # command: uvicorn main:app --reload --host=0.0.0.0 --port=10000 --workers=1
        # command: gunicorn main:app -w 4 -k uvicorn.workers.UvicornWorker -b 0.0.0.0:10000
    db:
      container_name: postgres
      image: postgres:15
      restart: always
      volumes:
        - ./postgres-data:/var/lib/postgresql/data
      ports:
        - "5555:5432"
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: postgres


